[project]
name = "ai-text-generation-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "demoji>=1.1.0",
    "emoji>=2.15.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
